In [2]:
# Standard Libraries
import pandas as pd
import numpy as np

In [3]:
# Display settings
pd.set_option('display.max_columns',None) # display all columns
pd.set_option('display.float_format', '{:.2f}'.format) # 2 decimal places

### Load Dataset

In [102]:
train = pd.read_csv('../data/raw/train.csv')
store = pd.read_csv('../data/raw/store.csv')
test = pd.read_csv('../data/raw/kaggle_test.csv')

C:\Users\kdako\AppData\Local\Temp\ipykernel_41684\1439695408.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv('../data/raw/train.csv')

In [103]:
# Shape of the data
print('Sales Shape: ', train.shape)
print('Store Shape: ', store.shape)
print('Test Shape: ', test.shape)

Sales Shape:  (1017209, 9)
Store Shape:  (1115, 10)
Test Shape:  (41088, 8)

In [104]:
train.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday'],
      dtype='object')

In [105]:
test.columns

Index(['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday',
       'SchoolHoliday'],
      dtype='object')

In [106]:
store.columns

Index(['Store', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval'],
      dtype='object')

In [107]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  object
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64
dtypes: int64(7), object(2)
memory usage: 69.8+ MB

In [108]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   object
 2   Assortment                 1115 non-null   object
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    object
dtypes: float64(5), int64(2), object(3)
memory usage: 87.2+ KB

In [109]:
train.describe()

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday
count,1017209.00,1017209.00,1017209.00,1017209.00,1017209.00,1017209.00,1017209.00
mean,558.43,4.00,5773.82,633.15,0.83,0.38,0.18
std,321.91,2.00,3849.93,464.41,0.38,0.49,0.38
min,1.00,1.00,0.00,0.00,0.00,0.00,0.00
25%,280.00,2.00,3727.00,405.00,1.00,0.00,0.00
50%,558.00,4.00,5744.00,609.00,1.00,0.00,0.00
75%,838.00,6.00,7856.00,837.00,1.00,1.00,0.00
max,1115.00,7.00,41551.00,7388.00,1.00,1.00,1.00

In [110]:
store.describe()

,Store,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1115.00,1112.00,761.00,761.00,1115.00,571.00,571.00
mean,558.00,5404.90,7.22,2008.67,0.51,23.60,2011.76
std,322.02,7663.17,3.21,6.20,0.50,14.14,1.67
min,1.00,20.00,1.00,1900.00,0.00,1.00,2009.00
25%,279.50,717.50,4.00,2006.00,0.00,13.00,2011.00
50%,558.00,2325.00,8.00,2010.00,1.00,22.00,2012.00
75%,836.50,6882.50,10.00,2013.00,1.00,37.00,2013.00
max,1115.00,75860.00,12.00,2015.00,1.00,50.00,2015.00

In [111]:
train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [112]:
test.head()

   Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4  2015-09-17  1.00      1            0              0
1   2      3          4  2015-09-17  1.00      1            0              0
2   3      7          4  2015-09-17  1.00      1            0              0
3   4      8          4  2015-09-17  1.00      1            0              0
4   5      9          4  2015-09-17  1.00      1            0              0

In [113]:
store.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.00,9.00,2008.00,0,NaN,NaN,NaN
1,2,a,a,570.00,11.00,2007.00,1,13.00,2010.00,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.00,12.00,2006.00,1,14.00,2011.00,"Jan,Apr,Jul,Oct"
3,4,c,c,620.00,9.00,2009.00,0,NaN,NaN,NaN
4,5,a,a,29910.00,4.00,2015.00,0,NaN,NaN,NaN

### Missing/Null Value Analysis

In [114]:
print('='*60)
print('Null Values in Train Data: ')
print('='*60)
train_null = pd.DataFrame({'Count of Missing values': train.isnull().sum(),
              '% of Missing Values': (train.isnull().sum()*100/len(train)).round(2)})
display(train_null) if train_null['Count of Missing values'].sum()>0 else print("No Null values in Train Data!")

============================================================
Null Values in Train Data:
============================================================
No Null values in Train Data!

In [115]:
print('='*60)
print('Null Values in Store Data: ')
print('='*60)
store_null = pd.DataFrame({'Count of Missing values': store.isnull().sum(),
              '% of Missing Values': (store.isnull().sum()*100/len(store)).round(2)})
display(store_null[store_null['Count of Missing values']>0]) if store_null['Count of Missing values'].sum()>0 else print("No Null values in Train Data!")

============================================================
Null Values in Store Data:
============================================================

                           Count of Missing values  % of Missing Values
CompetitionDistance                              3                 0.27
CompetitionOpenSinceMonth                      354                31.75
CompetitionOpenSinceYear                       354                31.75
Promo2SinceWeek                                544                48.79
Promo2SinceYear                                544                48.79
PromoInterval                                  544                48.79

In [116]:
print('='*60)
print('Null Values in Test Data: ')
print('='*60)
test_null = pd.DataFrame({'Count of Missing values': test.isnull().sum(),
              '% of Missing Values': (test.isnull().sum()*100/len(test)).round(2)})
display(test_null[test_null['Count of Missing values']>0]) if test_null['Count of Missing values'].sum()>0 else print("No Null values in Train Data!")

============================================================
Null Values in Test Data:
============================================================

      Count of Missing values  % of Missing Values
Open                       11                 0.03

In [117]:
# CompetitionDistance — fill with median
store['CompetitionDistance'] = store['CompetitionDistance'].fillna(store['CompetitionDistance'].median())

# Competition open since — fill with 0(either no known competitor or details unavailable)
store['CompetitionOpenSinceMonth'] = store['CompetitionOpenSinceMonth'].fillna(0)
store['CompetitionOpenSinceYear']  = store['CompetitionOpenSinceYear'].fillna(0)

# Promo2 fields — fill with 0(No Promo happened)
store['Promo2SinceWeek'] = store['Promo2SinceWeek'].fillna(0)
store['Promo2SinceYear'] = store['Promo2SinceYear'].fillna(0)

# PromoInterval — fill with 'None'
store['PromoInterval'] = store['PromoInterval'].fillna('None')

In [118]:
# Impute Open column with 1, keeping it open to predict its sales
test['Open'] = test['Open'].fillna(1)

In [119]:
train['Date'] = pd.to_datetime(train['Date'])
test['Date'] = pd.to_datetime(test['Date'])
print ("Train Data Date range: {} to {}".format(train['Date'].min(), train['Date'].max()))
print ("Test Data Date range: {} to {}".format(test['Date'].min(), test['Date'].max()))

Train Data Date range: 2013-01-01 00:00:00 to 2015-07-31 00:00:00
Test Data Date range: 2015-08-01 00:00:00 to 2015-09-17 00:00:00

### Duplicate Values

In [120]:
print("Duplicate Rows in Train :", train.duplicated().sum())
print("Duplicate Rows in Store :", store.duplicated().sum())
print("Duplicate Rows in Test :", test.duplicated().sum())

Duplicate Rows in Train : 0
Duplicate Rows in Store : 0
Duplicate Rows in Test : 0

### Merge Train & Store data

In [121]:
df_train = pd.merge(train,store,on = 'Store',how = 'left')
print("📦 train shape        :", train.shape)
print("📦 test shape         :", test.shape)
print("📦 store shape        :", store.shape)
print("📦 merged train shape :", df_train.shape)

print()
print('Train Data')
print("📅 Date range         :", df_train['Date'].min(), "→", df_train['Date'].max())
print("🏪 Total stores       :", df_train['Store'].nunique())
print("📋 Total columns      :", df_train.columns.tolist())
print()

print()
print('Test Data')
print("📅 Date range         :", test['Date'].min(), "→", test['Date'].max())
print("🏪 Total stores       :", test['Store'].nunique())
print("📋 Total columns      :", test.columns.tolist())
print()
print("✅ Merge successful!")

📦 train shape        : (1017209, 9)
📦 test shape         : (41088, 8)
📦 store shape        : (1115, 10)
📦 merged train shape : (1017209, 18)

Train Data
📅 Date range         : 2013-01-01 00:00:00 → 2015-07-31 00:00:00
🏪 Total stores       : 1115
📋 Total columns      : ['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval']


Test Data
📅 Date range         : 2015-08-01 00:00:00 → 2015-09-17 00:00:00
🏪 Total stores       : 856
📋 Total columns      : ['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday']

✅ Merge successful!

In [122]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 18 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1017209 non-null  float64
 12  CompetitionOpenSinceMonth  1017209 non-null  float64
 13  CompetitionOpenSinceYear   1017209 non-null  float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            1017209 non-null  float64
 16  Promo2SinceYear            1017209 non-null  float64
 17  PromoInterval              1017209 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(8), object(4)
memory usage: 147.5+ MB

In [123]:
df_train['StateHoliday'].unique()

array(['0', 'a', 'b', 'c', 0], dtype=object)

In [124]:
test['StateHoliday'].unique()

array(['0', 'a'], dtype=object)

In [125]:
df_train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.00,9.00,2008.00,0,0.00,0.00,None
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.00,11.00,2007.00,1,13.00,2010.00,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.00,12.00,2006.00,1,14.00,2011.00,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.00,9.00,2009.00,0,0.00,0.00,None
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.00,4.00,2015.00,0,0.00,0.00,None

### Save Cleaned Data

In [126]:
# ── Save merged dataframe to processed folder ─────────────────────
df_train.to_csv('../data/processed/merged.csv', index=False)
store.to_csv('../data/processed/store.csv', index=False)
test.to_csv('../data/processed/kaggle_test.csv', index=False)

print(f"✅ Files saved successfully!")
print()
print("🎉 Phase 1 — Data Loading & Cleaning COMPLETE!")

✅ Files saved successfully!

🎉 Phase 1 — Data Loading & Cleaning COMPLETE!